### ISSUE TITLE
Review and WX testing

### ISSUE THREAD

**Issue by domachine** [webdesignio/floorman#2]
To release the 1.0.0 milestone we should backcheck the experience of developing a website with this toolset.

**Comment by pA1nD** [comment]
Would be really nice to do:

``` jade
span(data-component='Inplace' data-props='{"name":"title1"}')
    | Sleek, Intuitive &amp; Performant.
```

**Comment by domachine** [comment]
This is sadly not the best idea since the value of an component can be any JSON value. The only thing I can think of is a mixin that turns this the body into a `data-props='{"name":"...","default":"Your html"}'` or something. But I couldn't find a way to turn a jade mixin block into a string.
